/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#006d3f",
        "primary-container": "#19e68c",
        "primary-fixed": "#57ffa6",
        "primary-fixed-dim": "#0de389",
        "on-primary": "#ffffff",
        "on-primary-container": "#006238",
        "on-primary-fixed": "#00210f",
        "on-primary-fixed-variant": "#00522e",
        "inverse-primary": "#0de389",
        secondary: "#00668a",
        "secondary-container": "#40c2fd",
        "secondary-fixed": "#c4e7ff",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#004d6a",
        "on-secondary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#004c69",
        tertiary: "#585e6f",
        "tertiary-container": "#c3c9dd",
        "tertiary-fixed": "#dce2f6",
        "tertiary-fixed-dim": "#c0c6da",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4e5465",
        "on-tertiary-fixed": "#151b2a",
        "on-tertiary-fixed-variant": "#404757",
        "wait-amber": "#F59E0B",
        error: "#ba1a1a",
        "error-rose": "#FB7185",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "ink-base": "#0F172A",
        "text-dark": "#0F172A",
        "text-light": "#E2E8F0",
        "slate-muted": "#64748B",
        outline: "#6b7b6e",
        "outline-variant": "#bacbbc",
        background: "#f7fafc",
        "on-background": "#181c1e",
        surface: "#f7fafc",
        "surface-bright": "#f7fafc",
        "surface-dim": "#d7dadc",
        "surface-tint": "#006d3f",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f6",
        "surface-container": "#ebeef0",
        "surface-container-high": "#e5e9eb",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#181c1e",
        "on-surface-variant": "#3b4a3f",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eef1f3",
        energy: {
          blue: "#0EA5E9",
          navy: "#0F172A",
          green: "#10B981",
          mint: "#D1FAE5",
        },
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui"],
        display: ["Space Grotesk", "Inter", "ui-sans-serif", "system-ui"],
        "body-base": ["Inter"],
        "body-bold": ["Inter"],
        "label-caps": ["Inter"],
        "headline-md": ["Space Grotesk"],
        "mobile-headline": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "display-2xl": ["Space Grotesk"],
        "stat-lg": ["Space Grotesk"],
      },
      fontSize: {
        "body-base": ["16px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" }],
        "body-bold": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.18em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "mobile-headline": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "display-2xl": ["60px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "stat-lg": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        base: "4px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      boxShadow: {
        soft: "0 18px 55px rgba(15, 23, 42, 0.10)",
        lift: "0 24px 70px rgba(15, 23, 42, 0.14)",
      },
    },
  },
  plugins: [],
};
